# Generated by Django 5.2.1 on 2025-05-20 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_follow"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="username",
            new_name="nome",
        ),
    ]
